### ISSUE TITLE
Packages under consideration in next update

### ISSUE THREAD

**Issue by robjhyndman** [cran-task-views/TimeSeries#11]
- [x] ForeComp
- [x] CFtime
- [x] costat
- [x] imputeFin
- [x] hwwntest

**Comment by pvanlaake** [comment]
Dear Rob and Rebecca,

I would like to suggest an additional package for the time series task view. The newly released CFtime package (https://cran.r-project.org/package=CFtime) encapsulates the CF time coordinate (http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#time-coordinate) and makes dealing with the different CF calendars transparent and straightforward. You may look at the vignette for some worked-out examples. The CF Metadata Conventions are widely used in packaging climate change model data and the time coordinate allows for nine different calendars, several of which are not compatible with POSIXt classes and processing without this utility package is thus tedious.

I would suggest including the CFtime package in the section on “Times and Dates” or “Time Series Classes”, with the suggested description:  The CFtime package encapsulates the CF Metadata Conventions “time” dimension, including all defined calendars. It facilitates the processing of climate change projection data.

I leave this classification up to your discretion.

Best,
Patrick

**Comment by robjhyndman** [comment]
CFtime and ForeComp added in https://github.com/cran-task-views/TimeSeries/commit/cd3a2732ca4cd4fb4f724cebf74aa67ae6125eb2
