### ISSUE TITLE
Add mvgam to appropriate sections

### ISSUE THREAD

**Issue by nicholasjclark** [cran-task-views/TimeSeries#24]
Hi @robjhyndman, thanks very much for maintaining this useful resource. [My package `mvgam` was just released to CRAN](https://cran.rstudio.com/web/packages/mvgam/index.html) so I'm hoping to add it to this list. It would most appropriately fit in the *Non-Gaussian time series* section in **Forecasting and Univariate Modeling** and in the *Multivariate state space models* and *Dynamic factor models* sections in **Multivariate Time Series Models**. Happy to provide a blurb if that makes it easier

**Comment by robjhyndman** [comment]
Thanks for letting us know. Added in https://github.com/cran-task-views/TimeSeries/commit/59fc4e9d710b211b67ecae59a4bb847063b583de
