### ISSUE TITLE
Addition to Time Series Data: `{cryptoQuotes}`

### ISSUE THREAD

**Issue by serkor1** [cran-task-views/TimeSeries#30]
HI @robjhyndman,

Would you consider adding [{cryptoQuotes}](https://github.com/serkor1/cryptoQuotes) under the topic **Time Series Data**? This package fetches cryptocurrency market data as `xts`-objects. It is already listed on *Finance*, but I found it relevant to list it here too.

**Example**
----------------
``` r
# load library
library(cryptoQuotes)

# extract daily
# data
tail(
  ETH <- get_quote(
    ticker   = "ETHUSDT",
    source   = "kraken",
    futures  = FALSE,
    interval = "1d",
    from     = Sys.Date() - 500,
    to       = Sys.Date()
  )
)
#>                        open    high     low   close    volume
#> 2024-06-08 02:00:00 3676.70 3708.02 3664.30 3682.52  563.3594
#> 2024-06-09 02:00:00 3680.61 3720.56 3668.95 3705.72 1684.2220
#> 2024-06-10 02:00:00 3703.67 3712.24 3646.50 3668.65  759.3700
#> 2024-06-11 02:00:00 3667.72 3671.02 3432.53 3498.60 2859.6136
#> 2024-06-12 02:00:00 3499.80 3654.83 3465.78 3561.23 2196.0433
#> 2024-06-13 02:00:00 3561.23 3561.23 3476.00 3497.10  621.4606
```

``` r

# print class
class(ETH)
#> [1] "xts" "zoo"
```

``` r
# simple chart
chart(
  ticker = ETH,
  main   = pline()
)
```

![](https://i.imgur.com/mDQ9ESn.png)

<sup>Created on 2024-06-13 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Best,

Serkan, author of {cryptoQuotes}

**Comment by robjhyndman** [comment]
Rather than add every finance package that includes time series data, we point people towards the Finance view at both the top and bottom of the page. Otherwise, there would be too much overlap between the two task views.

**Comment by serkor1** [comment]
Makes sense, thank you! 🫡
