### ISSUE TITLE
Add signal package to "Filters and Smoothing"

### ISSUE THREAD

**Issue by roaldarbol** [cran-task-views/TimeSeries#38]
Thanks for maintaining the task view, it's such a treasure trove of knowledge!

I'd like to recommend adding the [signal](https://cran.r-project.org/web/packages/signal/signal.pdf) package which provides a lot of filtering capabilities (from the Matlab and Octave functions). Important filters that it includes is a Butterworth filter, as well as a Savitsky-Golay filter, both of which are highly used in time series of movements (e.g. biomechanics, motor control, animal behaviour). I would recommend placing it under "Decomposition and Filtering", "Filters and smoothing".

**Comment by robjhyndman** [comment]
Added in https://github.com/cran-task-views/TimeSeries/commit/577e4ece5f17ca97bcd0585827d212786e2f44d7
