### ISSUE TITLE
Benchmark for rolling statistics

### ISSUE THREAD

**Issue by roaldarbol** [cran-task-views/TimeSeries#40]
Hi again! 
I've started doing some benchmarking of various rolling functions [here](https://roald-arboel.com/blog/posts/2024/10/03/Benchmark-rolling/). Would it make sense to include it in the section? And are there any particular features you would like to see tested? I currently haven't tested using dates or date intervals, but could definitely do that. :-)
Cheers,
Mikkel

**Comment by robjhyndman** [comment]
The task views are for brief descriptions of packages, and nothing more. So I don't think this would be appropriate, and would set a precedent that I'd rather not set.

Note that the `tsibble` package also has some rolling functions: `stretch_tsibble()`, `slide_tsibble()` and `tile_tsibble()`.

**Comment by roaldarbol** [comment]
Noted, that's completely fair. 😊 I'll check out `tsibble` too and see how it stacks up.
