### ISSUE TITLE
Add corbouli package to "Filters and Smoothing"

### ISSUE THREAD

**Issue by cadam00** [cran-task-views/TimeSeries#43]
Greetings,

I suggest adding [corbouli](https://cran.r-project.org/web/packages/corbouli/index.html) package that implements Corbae-Ouliaris Frequency Domain Filtering on "Filters and Smoothing" subsection of "Decomposition and Filtering" section.

Thanks,
Author of corbouli package.

**Comment by robjhyndman** [comment]
Added in https://github.com/cran-task-views/TimeSeries/commit/a6655a6c705bbfc292247638bd5a7b2dd3f96197
