### ISSUE TITLE
Packages for consideration

### ISSUE THREAD

**Issue by robjhyndman** [cran-task-views/TimeSeries#8]
- [x] WeightedPortTest
- [ ] imputeFin
- [x] rwebstat
- [x] bayesRecon
- [x] aion
- [x] portes

**Comment by trevorld** [comment]
Two new-ish packages on CRAN possibly worth including in the "Times and Dates" section:

* [{datetimeoffset}](https://github.com/trevorld/r-datetimeoffset)
* [{parttime}](https://github.com/dgkf/parttime/)

**Comment by robjhyndman** [comment]
Thanks for the suggestions. Both now added
